### PR TITLE
Use the new(?) field names for startTimestamp and endTimestamp.

### PR DESCRIPTION
**Pull request by TheJakeSchmidt**

### CODE REVIEW

**Comment by cbeley** [comment]
I assume you verified that the new values are still strings and in Ms? If so looks good to me.

**Comment by cbeley** [comment]
Strange choice by Google to rename this. I was a fan of the explicit Ms.

**Comment by TheJakeSchmidt** [comment]
No, I realized after sending this out that it still doesn't work this way; it doesn't error out but the timestamps are all zeroes, because it needs a Date.parse. Fix coming.

**Comment by cbeley** [comment]
Can you include an example of the new values? I may need to take a closer look later. Just on my phone.

**Comment by TheJakeSchmidt** [comment]
Definitely. This isn't urgent, so worth making sure I got it right. This is what the durations look like in the archive I downloaded today:
```
$ cat takeout-20220204T022511Z-001/Takeout/Location\ History/Semantic\ Location\ History/2014/2014_MARCH.json | jq .timelineObjects[0].activitySegment.duration |  head
{
  "startTimestamp": "2014-03-01T06:30:04.035Z",
  "endTimestamp": "2014-03-01T06:36:12.676Z"
}
```

Grep shows no instances of "TimestampMs" in these files.

I updated the PR to include the code in googleTakeoutToGeoJSON.mjs, and also to use Date.parse() everywhere on the new fields. This is the version of the code I ran on my own location history, and the dates look right (earliest and latest plus a spot check of two specific days).

**Comment by cbeley** [comment]
Unfortunately, date.parse is generally considered unsafe. It's behavior is implementation specific and may also have unexpected behavior if a new or malformed date string is passed to it (from what was expected at least).

I believe date-fns, which I already pulled into this repo has some facilities for parsing what I bet is an ISO date string. 

If you'd like to give it a shot, feel free, otherwise I'll take a deeper look later. Unfortunately, I was a bit lazy with this project, so there are no tests. :/ One day.

**Comment by TheJakeSchmidt** [comment]
Oh, good to know (I'm not very familiar with Javascript APIs anymore), let me convert those calls to use date-fns.

**Comment by TheJakeSchmidt** [comment]
Switched the `Date.parse`s to `parseISO`s. The code still works on my Takeout data from February, and produces identical output as the previous version.

**Comment by TheJakeSchmidt** [comment]
My bad, I wasn't actually testing the local changes when I tested earlier, so it wasn't quite working (parseISO returns a date, but I was treating it like an integer). This version is rebased on #1, correctly tested, and working.

**Comment by cbeley** [comment]
@TheJakeSchmidt Hey, I just wanted to say I really appreciate your interest in this! I really want to get this merged, but things have been super hectic for me right now. 

As soon as I can confirm (and maybe throw in some integration tests), I'll get this merged and re-publish!

**Comment by cbeley** [comment]
I've been pretty busy between a new job and life that I have not had a chance to verify this. However, given some interest in the tool, and this PR looking OK at a glance, i'm going to go ahead and publish this.

Thanks again!

**Comment by cbeley** [comment]
@TheJakeSchmidt @developStorm This is now published in 0.1.0. Please open a new issue and or PR if you have any issues!

**Pull request merged**
